### ISSUE TITLE
图片外链问题

### ISSUE THREAD

**Issue by Undertone0809** [Cheese-Yu/yuque-sync#1]
你好，我想问问md图片的外链问题怎么解决呢？如果md中的图片链接如果可以支持转换成图床的就更好了，我写了一个可以把语雀手动导出md的图片链接批量转换成图床链接的转换器，作者可以借鉴借鉴，欢迎fork学习参考一下，期待添加图床的功能。虽然使用python写的，但是功能上还是相似的。[https://github.com/Undertone0809/md-img-converter](https://github.com/Undertone0809/md-img-converter)

**Comment by Cheese-Yu** [comment]
非常感谢你的建议，现已支持图片外链上传至GitHub。
