### ISSUE TITLE
图片上传重复问题

### ISSUE THREAD

**Issue by Cheese-Yu** [Cheese-Yu/yuque-sync#2]
如果文章更新，图片会重新上传一遍，期望：已经上传过的图片不要再上传一遍了

**Comment by mr-aray** [comment]
自己给自己提issue嘛😂

**Comment by Cheese-Yu** [comment]
> 自己给自己提issue嘛😂

做记录，防止忘记了

**Comment by Cheese-Yu** [comment]
已解决，根据目录和文章等规则生成图片的文件名，而不是用随机的uuid。如果文章更新图片还是会重新传一遍，不过应该不会有重复的图片了
